name: Linux installer

env:
  ARTIFACT: neurotic-1.4.0-Linux-x86_64.sh

on: push

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2

      - name: Setup Miniconda
        uses: goanpeca/setup-miniconda@v1.0.2
        with:
          auto-update-conda: true

      - name: Install constructor
        shell: bash -l {0}
        run: |
          conda install -y -q -c conda-forge constructor=3.0.0
          conda env list
          conda list

      - name: Build installer
        shell: bash -l {0}
        run: constructor

      - uses: actions/upload-artifact@v1
        with:
          name: ${{ env.ARTIFACT }}
          path: ${{ env.ARTIFACT }}
