name: Windows installer

env:
  ARTIFACT: neurotic-1.5.0-Windows-x86_64.exe

on: push

jobs:
  build-windows:
    runs-on: windows-latest
    steps:

      - uses: actions/checkout@v2

      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v2.0.1

      - name: Install constructor
        shell: bash -l {0}
        run: |
          conda install -y -q -c conda-forge constructor
          conda env list
          conda list

      - name: Build installer
        shell: bash -l {0}
        run: constructor

      - uses: actions/upload-artifact@v2
        with:
          name: ${{ env.ARTIFACT }}
          path: ${{ env.ARTIFACT }}
